version: '3'
services:
    apache:
        build: .docker/apache
        container_name: ubi_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/ubi
        depends_on:
          - php


    db:
      image: mariadb:latest
      container_name: ubi_mariadb
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: ubi_myadmin
      links:
        - "db:db"
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
      restart: always
      ports:
        - "8080:80"
      volumes:
        - "/sessions"

    php:
        build: .docker/php
        container_name: ubi_php
        volumes:
          - .:/home/wwwroot/ubi
        environment:
          - maildev_host=ubi_maildev
        depends_on:
          - maildev
          - db



    maildev:
      image: djfarrelly/maildev
      container_name: ubi_maildev
      ports:
        - 8001:80

